server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kaoyan_share?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
#  cloud:
#    nacos:
#      server-addr: http://192.168.200.128:8848
#      config:
#        server-addr: http://192.168.200.128:8848
#        shared-configs:
#          - data-id: test.yaml
#            group: DEFAULT_GROUP
#            refresh: true
#      discovery:
#        server-addr: http://192.168.200.128:8848
#  application:
#    name: ceshi


test:
  hh: hello world